default:
  outputs:
    dev:
      account: AWLFVMB-BCB57947
      database: analytics
      password: Sachin@10
      role: analyticsengineer
      schema: DBT_CORE_AG
      threads: 3
      type: snowflake
      user: Sachin
      warehouse: transform_wh
  target: dev
